services:
  mongodb:
    image: mongo:7
    container_name: ecommerce-mongo
    ports:
      - "27019:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: ecommerce-backend
    ports:
      - "8001:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    volumes:
      - uploads-data:/app/uploads

  frontend:
    build: ./frontend
    container_name: ecommerce-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo-data:
  uploads-data:
